language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
gemfile:
  - gemfiles/rails5.2.gemfile
  - gemfiles/rails5.1.gemfile
  - gemfiles/rails5.0.gemfile
before_install: gem install bundler
bundler_args: ""
before_script:
  - rm spec/database.yml && mv spec/database.travis.yml spec/database.yml
  - psql -c 'create database hierarchical_query_test;' -U postgres
script: 'bundle exec rspec'
notifications:
  recipients:
    - zachaysan@gmail.com
