language: ruby
rvm:
  - 1.9.3
  - 2.0.0
gemfile:
  - gemfiles/rails3.1.gemfile
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.0.gemfile
bundler_args: --without local
before_script:
  - rm spec/database.yml && mv spec/database.travis.yml spec/database.yml
  - psql -c 'create database hierarchical_query_test;' -U postgres
script: 'bundle exec rspec'
notifications:
  recipients:
    - amikhailov83@gmail.com