language: ruby
rvm:
  - 2.0.0
  - 2.1.2
  - 2.2
gemfile:
  - gemfiles/rails3.1.gemfile
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.0.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
before_install: gem install bundler
bundler_args: ""
before_script:
  - rm spec/database.yml && mv spec/database.travis.yml spec/database.yml
  - psql -c 'create database hierarchical_query_test;' -U postgres
script: 'bundle exec rspec'
notifications:
  recipients:
    - amikhailov83@gmail.com
